import turtle
import time

def draw_flower(x, y):
    t = turtle.Turtle()
    t.speed(10)
    t.penup()
    t.goto(x, y) 
    t.pendown()
    t.color("red")
    for i in range(36):
        t.forward(50)
        t.left(170)
    t.penup()
    t.goto(x + 20, y)
    t.pendown()
    t.color("yellow")
    t.begin_fill()
    t.circle(20)
    t.end_fill()
    t.color("black")
    t.penup()
    t.goto(x + 30, y + 10)
    t.pendown()
    t.write("happy new year", align="center", font=("Arial", 12, "bold"))
    t.penup()

t = turtle.Turtle()
t.speed(10)
t.penup()
t.goto(-100, 200)
t.pendown()
t.color("red")
t.write("CHÚC", align="left", font=("Arial", 24, "bold"))
time.sleep(1)
t.penup()
t.goto(-100, 150)
t.pendown()
t.color("blue")
t.write("MỪNG", align="left", font=("Arial", 24, "bold"))
time.sleep(1)
t.penup()
t.goto(-100, 100)
t.pendown()
t.color("pink")
t.write("NĂM", align="left", font=("Arial", 24, "bold"))
time.sleep(1)
t.penup()
t.goto(-100, 50)
t.pendown()
t.color("purple")
t.write("MỚI", align="left", font=("Arial", 24, "bold"))
time.sleep(1)
t.penup()
t.goto(-100, 0)
t.pendown()
t.color("red")
t.write("2023", align="left", font=("Arial", 24, "bold"))
time.sleep(1)
t.penup()
t.goto(-100, -50)
t.pendown()
t.color("yellow")
t.write("NĂM MỚI VUI VẺ", align="left", font=("Arial", 24, "bold"))
time.sleep(1)
t.penup()
t.goto(-100, -100)
t.pendown()
t.color("red")
t.write("LÌ XÌ TÔI ĐI !!!", align="left", font=("Arial", 30, "bold"))

draw_flower(-200,200)
draw_flower(200, 200)
draw_flower(-200, -200)
draw_flower(200, -200)

turtle.done()
